### ISSUE TITLE
Episode Rendering

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coord-sim#164]
Currently, even with our eval notebooks, it's still a bit cumbersome to see what's going on. It would be nice if we could render and create a short video showing what happened during an episode: Where were which VNFs placed over time? Ideally also info about which VNFs where connected and how much traffic was sent where.
This would also be nice for possible future demos of our work.

I did something similar for another project using [matplotlib animations](https://matplotlib.org/3.3.0/api/animation_api.html). It works well, generates HTML5 videos (potentially also gifs or mp4, but we don't need that), and is really useful to see what's going on in a complex scenario. For the other project, my visualization currently looks like this:

![animation](https://user-images.githubusercontent.com/28340802/88938540-c7a23080-d285-11ea-933b-d178bab52f30.gif)

This animation might not make sense, since the problem is completely different. But it gives you an idea. Basically, it shows the environment state over time in a simple to understand and visual way.
As I starting point, we should first just plot the network and the placement over time.

I'll provide my code in a comment below.

**Comment by stefanbschneider** [comment]
This is the render function inside the environment:

```python
def render(self, mode='human'):
        """Plot and visualize the current status of the world. Return the patch of actors for animation."""
        # list of matplotlib "artists", which can be used to create animations
        patch = []

        # limit to map borders
        plt.xlim(0, self.map.width)
        plt.ylim(0, self.map.height)

        # users & connections
        # show utility as red to yellow to green. use color map for [0,1) --> normalize utility first
        colormap = cm.get_cmap('RdYlGn')
        norm = plt.Normalize(-20, 20)

        for ue in self.ue_list:
            # plot connections to all BS
            for bs, dr in ue.bs_dr.items():
                color = colormap(norm(log_utility(dr)))
                # add black background/borders for lines to make them better visible if the utility color is too light
                patch.extend(plt.plot([ue.pos.x, bs.pos.x], [ue.pos.y, bs.pos.y], color=color,
                                      path_effects=[pe.SimpleLineShadow(shadow_color='black'), pe.Normal()]))
                                      # path_effects=[pe.Stroke(linewidth=2, foreground='black'), pe.Normal()]))
            # plot UE
            patch.extend(ue.plot())

        # base stations
        for bs in self.bs_list:
            patch.extend(bs.plot())

        # title isn't redrawn in animation (out of box) --> static --> show time as text inside box, top-right corner
        patch.append(plt.title(type(self).__name__))
        # extra info: time step, total data rate & utility
        patch.append(plt.text(0.9*self.map.width, 0.95*self.map.height, f"t={self.time}"))
        patch.append(plt.text(0.9*self.map.width, 0.9*self.map.height, f"dr={self.total_dr:.2f}"))
        patch.append(plt.text(0.9*self.map.width, 0.85*self.map.height, f"util={self.total_utility:.2f}"))

        # legend doesn't change --> only draw once at the beginning
        # if self.time == 0:
        #     plt.legend(loc='upper left')
        return patch
```

This is the main simulation loop, where rendering is called if it's enabled. Just enabled for a single testing episode - not for training!

``` python
if render is not None:
            fig = plt.figure(figsize=env.map.figsize)
            # equal aspect ratio to avoid distortions
            plt.gca().set_aspect('equal')

        # run until episode ends
        patches = []
        done = False
        obs = env.reset()
        while not done:
            if render is not None:
                patches.append(env.render())
                if render == 'plot':
                    plt.show()

            # get and apply action
            if self.multi_agent_env:
                obs, reward, done, info = self.apply_action_multi_agent(obs, env)
            else:
                obs, reward, done, info = self.apply_action_single_agent(obs, env)

        # create the animation
        if render is not None:
            fig.tight_layout()
            self.save_animation(fig, patches, render)
```

Finally, the function to save the animation to file, called at the end of an episode:

```python
def save_animation(self, fig, patches, mode):
        """
        Create and save matplotlib animation
        :param fig: Matplotlib figure
        :param patches: List of patches to draw for each step in the animation
        :param mode: How to save the animation. Options: 'video' (=html5) or 'gif' (requires ImageMagick)
        """
        render_modes = SUPPORTED_RENDER - {None}
        assert mode in render_modes, f"Render mode {mode} not in {render_modes}"
        anim = matplotlib.animation.ArtistAnimation(fig, patches, repeat=False)

        # save html5 video
        if mode == 'html' or mode == 'both':
            html = anim.to_html5_video()
            with open(f'{VIDEO_DIR}/{self.result_filename}.html', 'w') as f:
                f.write(html)
            self.log.info('Video saved', path=f'{VIDEO_DIR}/{self.result_filename}.html')

        # save gif; requires external dependency ImageMagick
        if mode == 'gif' or mode == 'both':
            try:
                anim.save(f'{VIDEO_DIR}/{self.result_filename}.gif', writer='imagemagick')
                self.log.info('Gif saved', path=f'{VIDEO_DIR}/{self.result_filename}.gif')
            except TypeError:
                self.log.error('ImageMagick needs to be installed for saving gifs.')
```

These are just hints, you may do it differently of course.

**Comment by stefanbschneider** [comment]
Btw, NetworkX natively supports plotting with Matplotlib: https://networkx.github.io/documentation/stable/reference/drawing.html#module-networkx.drawing.nx_pylab
So that should help in plotting our network. Ideally, use the GPS coordinates to place the nodes.

**Comment by stefanbschneider** [comment]
Here a few things to fix:

`animation -h` should show the available CLI commands but breaks.

```
animation -h
Traceback (most recent call last):
  File "C:\Users\Stefan\git-repos\work\swc\venv\Scripts\animation-script.py", line 11, in <module>
    load_entry_point('coord-sim', 'console_scripts', 'animation')()
  File "c:\users\stefan\git-repos\work\swc\coord-sim\src\animations\animations.py", line 553, in main
    if kwargs["results_dir"]:
KeyError: 'results_dir'
```

Apparently all other commands also break with the same error:

```
C:\Users\Stefan\git-repos\work\swc\rl-coordination>animation --results_dir results\agent_obs2_f05d05reward_64a_64c_099gam_00001tau_001alp_0001dec\triangle-in1-cap1-delay10\abc\det-arrival10_det-size001_duration100\2020-09-16_
08-51-16_seed3630 --show_tests
Traceback (most recent call last):
  File "C:\Users\Stefan\git-repos\work\swc\venv\Scripts\animation-script.py", line 11, in <module>
    load_entry_point('coord-sim', 'console_scripts', 'animation')()
  File "c:\users\stefan\git-repos\work\swc\coord-sim\src\animations\animations.py", line 553, in main
    if kwargs["results_dir"]:
KeyError: 'results_dir'
```

**Comment by stefanbschneider** [comment]
Running on Ubuntu (tango1):

```
stefan@fgcn-tango-1:~/realvnf/rl-coordination$ animation -h
Traceback (most recent call last):
  File "/home/stefan/realvnf/venv/bin/animation", line 11, in <module>
    load_entry_point('coord-sim', 'console_scripts', 'animation')()
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/stefan/realvnf/coord-sim/src/animations/animations.py", line 12, in <module>
    matplotlib.use('TkAgg')
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py", line 295, in wrapper
    return func(*args, **kwargs)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py", line 356, in wrapper
    return func(*args, **kwargs)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/__init__.py", line 1254, in use
    plt.switch_backend(name)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/backends/_backend_tk.py", line 6, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

`sudo apt install python3-tk` didn't help since it was already installed.

**Comment by stefanbschneider** [comment]
Next problem:

```
animation -h
Traceback (most recent call last):
  File "/home/stefan/realvnf/venv/bin/animation", line 11, in <module>
    load_entry_point('coord-sim', 'console_scripts', 'animation')()
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/stefan/realvnf/coord-sim/src/animations/animations.py", line 12, in <module>
    matplotlib.use('TkAgg')
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py", line 295, in wrapper
    return func(*args, **kwargs)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py", line 356, in wrapper
    return func(*args, **kwargs)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/__init__.py", line 1254, in use
    plt.switch_backend(name)
  File "/home/stefan/realvnf/venv/lib/python3.7/site-packages/matplotlib-3.2.0rc1-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 237, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```

I guess, this could solve it: https://stackoverflow.com/a/57636427/2745116

**Comment by stefanbschneider** [comment]
@RafaelSche There seems to be an error when trying to visualize a network that does not have GPS positions of the nodes given in the network file:

```
(venv) C:\Users\Stefan\git-repos\work\swc\rl-coordination\results>animation --results_dir agent_obs1_msr09mpd30reward_64a_64c_099gam_00001tau_001alp_0001dec\2node-in1-cap1-delay10\a\det-arrival3_det-size001_dur100\2020-09-21_09-54-0
5_seed6516\test-2020-09-21_09-54-05_seed6516 --save html
{'results_dir': 'agent_obs1_msr09mpd30reward_64a_64c_099gam_00001tau_001alp_0001dec\\2node-in1-cap1-delay10\\a\\det-arrival3_det-size001_dur100\\2020-09-21_09-54-05_seed6516\\test-2020-09-21_09-54-05_seed6516', 'test_dir': None, 'sh
ow_tests': False, 'show': False, 'save': 'html'}
Creating PlacementAnime object...
Traceback (most recent call last):
  File "C:\Users\Stefan\git-repos\work\swc\venv\Scripts\animation-script.py", line 11, in <module>
    load_entry_point('coord-sim', 'console_scripts', 'animation')()
  File "c:\users\stefan\git-repos\work\swc\coord-sim\src\animations\animations.py", line 584, in main
    pa = PlacementAnime(kwargs["test_dir"])
  File "c:\users\stefan\git-repos\work\swc\coord-sim\src\animations\animations.py", line 77, in __init__
    self.edge_pos = self.determine_edge_pos()
  File "c:\users\stefan\git-repos\work\swc\coord-sim\src\animations\animations.py", line 193, in determine_edge_pos
    edge_pos[(source, target)] = (self.node_pos[source] + self.node_pos[target])/2
TypeError: 'NoneType' object is not subscriptable
```

Our own dummy networks may not have a node position. The animation should still work. Eg, assign a fixed position at the beginning yourself.
